name: PrivateMines
version: "1.1"
main: me.bristermitten.privatemines.PrivateMines
authors: [BristerMitten, UntouchedOdin0]
website: github.com/knightzmc
depend:
  - WorldEdit
  - FastAsyncWorldEdit
  - Vault
  - WorldGuard
  - Citizens
  - AutoSell
